feat(console): update page titles in pezzo consoles
pezzolabs/pezzo pull request #221
Opened 2023-09-27 14:43 UTC by senderh55

releted to #192

2023-09-27 16:05 UTC, arielweinberger requested changes
Looks great overall! Let's try the changes I've suggested.

2023-09-27 16:05 UTC, arielweinberger commented on apps/console/src/app/pages/InfoPage.tsx
> +  usePageTitle("Login");
```suggestion
  usePageTitle("Info");
```

2023-09-27 16:05 UTC, arielweinberger commented on apps/console/src/app/pages/organizations/OrgPage.tsx
> +  usePageTitle(`${organization?.name || "Organization"}`);
```suggestion
  usePageTitle(organization?.name);
```
With the fallback we don't need the `||` here.

2023-09-27 16:05 UTC, arielweinberger commented on apps/console/src/app/pages/organizations/onboarding/OnboardingPage.tsx
> +  usePageTitle(`Onboarding ${organization?.name || ""}`);
```suggestion
  usePageTitle("Onboarding");
```
I think this is enough.

2023-09-27 16:05 UTC, arielweinberger commented on apps/console/src/app/pages/projects/ProjectPage.tsx
> +  usePageTitle(project?.name || "Project");
```suggestion
  usePageTitle(project?.name);
```
With the fallback we don't need the `||`

2023-09-27 16:05 UTC, arielweinberger commented on apps/console/src/app/pages/prompts/PromptPage.tsx
> +  usePageTitle(prompt?.name || "Prompt");
```suggestion
  usePageTitle(prompt?.name);
```

2023-09-27 16:05 UTC, arielweinberger commented on apps/console/src/app/pages/prompts/PromptsPage.tsx
> +  usePageTitle(`${project.name || ""} prompts`);
```suggestion
  usePageTitle(project?.name && `${project.name} Prompts`);
```

2023-09-27 17:59 UTC, senderh55 reviewed
Thanks!

2023-09-28 11:08 UTC, arielweinberger commented
Tested, seems to work very well. Well done, @senderh55

2023-09-28 11:09 UTC, arielweinberger approved these changes

2023-09-28 11:10 UTC, merged