fix(server+clent): added validitions in both fe and be
pezzolabs/pezzo pull request #241
Opened 2023-10-11 20:51 UTC by adityapuri75

resolved form validation issue in api field

2023-10-11 22:16 UTC, arielweinberger requested changes

2023-10-11 22:16 UTC, arielweinberger commented on apps/console/src/app/components/api-keys/ProviderApiKeyListItem.tsx
> +      });
Please don't use the `messageApi` for this. We have the ability to render errors under their input field as we do in other places (e.g. prompt creation modal, environment creation modal). Suits better.

2023-10-11 22:17 UTC, arielweinberger commented
Thanks for putting the time @adityapuri75. I've left some feedback. Please make sure to run `npx nx format:write --all` at the root of the repo to format it before committing, this way CI will pass.

2023-10-12 06:01 UTC, adityapuri75 commented
Thanks for the feedback @arielweinberger, i have updated the branch as you suggested. i don’t have much experience with the fe but i have took reference from the other files and made changes Please Review.

2023-10-12 16:00 UTC, arielweinberger commented on apps/console/src/app/components/api-keys/ProviderApiKeyListItem.tsx
> +  const [form] = Form.useForm<{ name: string }>();
```suggestion
  const [form] = Form.useForm<{ apiKey: string }>();
```

2023-10-12 17:11 UTC, adityapuri75 commented
Hello @arielweinberger thanks for the feedback on my commit, can i start working on issue  #238

2023-10-12 17:29 UTC, arielweinberger commented
@adityapuri75 Please comment there so I can assign it to you. Thanks for this contribution!

2023-10-12 17:29 UTC, arielweinberger approved these changes

2023-10-12 17:29 UTC, merged